### ISSUE TITLE
Is this mantained?

### ISSUE THREAD

**Issue by ZerdoX-x** [agnipau/telegram-palette-gen#11]
@agnipau if not, i'll fork it and review & merge pull requests and try to resolve issues

**Comment by ZerdoX-x** [comment]
and guy who is reading this. put thumbs up reaction if you want this to be mantained

**Comment by agnipau** [comment]
It is not. Also keep in mind that Telegram changed the theme format, so now the program needs a rewrite and can only change the palette but not the background image.
